# Uncomment the next line to define a global platform for your project
platform :ios, ’10.3’

target 'SStreamliner' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Alamofire', '~> 4.4'
  pod 'SwiftyJSON'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod 'TwitterKit'

  # Pods for SStreamliner

end
